# Generated by Django 4.2.1 on 2023-05-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidadeativa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemonstracoesContabeis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Título"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, upload_to="transparencia/dc/%Y/%m/%d/"
                    ),
                ),
            ],
        ),
    ]
