# Generated by Django 4.2.1 on 2023-05-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidadeativa", "0002_demonstracoescontabeis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demonstracoescontabeis",
            options={
                "verbose_name": "Demonstrações Contábeis",
                "verbose_name_plural": "Demonstrações Contábeis",
            },
        ),
        migrations.AddField(
            model_name="demonstracoescontabeis",
            name="tipo_relatorio",
            field=models.CharField(
                choices=[
                    ("DC", "Demonstrativos Contábeis E Financeiros"),
                    ("TM", "Termos De Parceiros"),
                    ("CE", "Certidões"),
                    ("ED", "Editais"),
                ],
                default="DC",
                max_length=2,
            ),
        ),
    ]
