# Generated by Django 4.2.1 on 2023-05-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidadeativa", "0004_rename_demonstracoescontabeis_relatorio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatorio",
            options={"verbose_name": "Relatório", "verbose_name_plural": "Relatórios"},
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="arquivo",
            field=models.FileField(upload_to="transparencia/dc/%Y/%m/%d/"),
        ),
    ]
