# Generated by Django 4.2.1 on 2023-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidadeativa", "0005_alter_relatorio_options_alter_relatorio_arquivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("assunto", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
            ],
        ),
    ]
